### ISSUE TITLE
when setting the node channel attribute, msg.channel is ignored

### ISSUE THREAD

**Issue by DyosTheNerd** [yayadrian/node-red-slack#12] opened 2017-02-28 15:49 UTC
When I set the node channel attribute, the msg.channel attribute is ignored, meaning I cannot send to a different channel. It might be by design (then a comment in the doc might be enough, that node attribute takes precedence over msg.channel), but from a usability perspective, I think it makes sense to have the precedence the other way around. I could use the node s attribute channel as a debug channel, and then have the messages specify their channel once I go into "production".

**Comment by travisghansen** [comment] 2019-03-19 03:42
This is common practice with `Node-RED` nodes and likely by design.  The recently released `2.0.0` is totally different approach so closing this down.

**Closed as completed by travisghansen** 2019-03-19 03:42 UTC
